---
rules:
  # Setting these limits causes failed builds which can be confusing
  concurrency-limits:
    disable: true
  # disable until all runners in the wild really support it
  self-repository:
    disable: true
