/*
 * Copyright (c) 2021 - UPMEM
 */

#ifndef DPU_CHARACTERISTICS_H
#define DPU_CHARACTERISTICS_H

#define DPU_NR_THREADS 24
#define DPU_NR_ATOMIC_BITS 256
#define DPU_NR_WORK_REGS 24

#endif /* DPU_CHARACTERISTICS_H */
