name: 'Setup build matrix'

outputs:
  build-matrix:
    description: 'Build matrix'
    value: ${{ steps.output-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
  - id: output-os
    run: echo "::set-output name=os::[\"ubuntu-latest\"]"
  - id: output-matrix
    run: echo "::set-output name=matrix::{\"os\":${{ steps.ouput-os.outputs.os }},\"java\":[\"17\"],\"distribution\":[\"temurin\"]}"
    shell: bash