import com.ibm.icu.lang.UCharacter
import com.ibm.icu.lang.UScript
import com.ibm.icu.util.VersionInfo
import java.nio.file.Paths
import java.util.Locale

def icuVersion = VersionInfo.ICU_VERSION.toString()
def unicodeVersion = UCharacter.getUnicodeVersion().toString()

def outputFile = Paths.get(args[0])

def generateFoldMappings() {
  StringBuilder sb = new StringBuilder()
  int lastScript = -1
  int count = 0

  for (int c = 0; c < 0x10000; c++) {
    int folded = UCharacter.foldCase(c, true)
    if (folded != c && folded >= 0 && folded <= 0xFFFF) {
      int script = UScript.getScript(c)
      String scriptName = UScript.getName(script)

      if (script != lastScript) {
        if (count > 0) {
          sb.append("\n")
        }
        sb.append("\n    // ${scriptName}")
        lastScript = script
      }
      String fromChar = new String(Character.toChars(c))
      String toChar = new String(Character.toChars(folded))
      sb.append(String.format(Locale.ROOT, "\n    0x%04X, 0x%04X, // %s -> %s", c, folded, fromChar, toChar))
      count++
    }
  }
  return sb.toString()
}

def code = """
// DO NOT EDIT THIS FILE! Use "gradlew generateFoldTable tidy" to recreate.

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.lucene.util;

/**
 * Flat lookup table for Unicode simple case folding of BMP codepoints.
 * Generated using ICU4J v${icuVersion}, unicode version: ${unicodeVersion}.
 */
final class FoldTable {
  private FoldTable() {}

  static final char[] TABLE = new char[0x10000];

  static {
    for (int i = 0; i < TABLE.length; i++) {
      TABLE[i] = (char) i;
    }
    int[] mappings = {${generateFoldMappings()}
    };
    for (int i = 0; i < mappings.length; i += 2) {
      TABLE[mappings[i]] = (char) mappings[i + 1];
    }
  }
}
"""
outputFile.setText(code, "UTF-8")
