name: Documentation Improvement
description: File a task relates to documentation
labels: ["type:documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
