name: Install eclint
description: Installs eclint from cache, or builds it

inputs:
  eclint-version:
    required: false
    description: "eclint version to use"
    default: "v0.5.1"

runs:
  using: "composite"
  steps:
    - name: Cache eclint binary
      id: cache-eclint
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: ~/.local/bin/eclint
        key: eclint-${{ inputs.eclint-version }}-${{ runner.os }}-${{ runner.arch }}
    - name: Setup go
      if: steps.cache-eclint.outputs.cache-hit != 'true'
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: '1.24'
        cache: false
    - name: Install eclint
      if: steps.cache-eclint.outputs.cache-hit != 'true'
      run: GOBIN=${HOME}/.local/bin go install gitlab.com/greut/eclint/cmd/eclint@${ECLINT_VERSION}
      shell: bash
      env:
        ECLINT_VERSION: ${{ inputs.eclint-version }}
    - name: Configure gradle
      run: echo "lucene.tool.eclint=eclint" >> build-options.local.properties
      shell: bash
