// DO NOT EDIT THIS FILE! Use "gradlew regenerateSimpleCaseFolding tidy" to recreate.

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.lucene.util;

/**
 * Switch-based Unicode simple case folding for the 226 codepoints where folding differs from {@link
 * Character#toLowerCase(int)}. Generated using ICU4J v78.3.0.0, unicode version: 17.0.0.0.
 *
 * @see <a href="https://www.unicode.org/Public/latest/ucd/CaseFolding.txt">Unicode Case Folding
 *     mappings</a>
 */
final class SimpleCaseFolding {
  private SimpleCaseFolding() {}

  /**
   * Returns the simple case fold of {@code c}, falling back to {@link Character#toLowerCase(int)}
   * for codepoints where fold equals lowercase.
   */
  static int fold(int c) {
    switch (c) {
      // Common
      case 0x00B5:
        return 0x03BC; // µ → μ

      // Latin
      case 0x0130:
        return 0x0130; // İ → İ
      case 0x017F:
        return 0x0073; // ſ → s

      // Inherited
      case 0x0345:
        return 0x03B9; // ͅ → ι

      // Greek
      case 0x03C2:
        return 0x03C3; // ς → σ
      case 0x03D0:
        return 0x03B2; // ϐ → β
      case 0x03D1:
        return 0x03B8; // ϑ → θ
      case 0x03D5:
        return 0x03C6; // ϕ → φ
      case 0x03D6:
        return 0x03C0; // ϖ → π
      case 0x03F0:
        return 0x03BA; // ϰ → κ
      case 0x03F1:
        return 0x03C1; // ϱ → ρ
      case 0x03F5:
        return 0x03B5; // ϵ → ε

      // Cherokee
      case 0x13A0:
        return 0x13A0; // Ꭰ → Ꭰ
      case 0x13A1:
        return 0x13A1; // Ꭱ → Ꭱ
      case 0x13A2:
        return 0x13A2; // Ꭲ → Ꭲ
      case 0x13A3:
        return 0x13A3; // Ꭳ → Ꭳ
      case 0x13A4:
        return 0x13A4; // Ꭴ → Ꭴ
      case 0x13A5:
        return 0x13A5; // Ꭵ → Ꭵ
      case 0x13A6:
        return 0x13A6; // Ꭶ → Ꭶ
      case 0x13A7:
        return 0x13A7; // Ꭷ → Ꭷ
      case 0x13A8:
        return 0x13A8; // Ꭸ → Ꭸ
      case 0x13A9:
        return 0x13A9; // Ꭹ → Ꭹ
      case 0x13AA:
        return 0x13AA; // Ꭺ → Ꭺ
      case 0x13AB:
        return 0x13AB; // Ꭻ → Ꭻ
      case 0x13AC:
        return 0x13AC; // Ꭼ → Ꭼ
      case 0x13AD:
        return 0x13AD; // Ꭽ → Ꭽ
      case 0x13AE:
        return 0x13AE; // Ꭾ → Ꭾ
      case 0x13AF:
        return 0x13AF; // Ꭿ → Ꭿ
      case 0x13B0:
        return 0x13B0; // Ꮀ → Ꮀ
      case 0x13B1:
        return 0x13B1; // Ꮁ → Ꮁ
      case 0x13B2:
        return 0x13B2; // Ꮂ → Ꮂ
      case 0x13B3:
        return 0x13B3; // Ꮃ → Ꮃ
      case 0x13B4:
        return 0x13B4; // Ꮄ → Ꮄ
      case 0x13B5:
        return 0x13B5; // Ꮅ → Ꮅ
      case 0x13B6:
        return 0x13B6; // Ꮆ → Ꮆ
      case 0x13B7:
        return 0x13B7; // Ꮇ → Ꮇ
      case 0x13B8:
        return 0x13B8; // Ꮈ → Ꮈ
      case 0x13B9:
        return 0x13B9; // Ꮉ → Ꮉ
      case 0x13BA:
        return 0x13BA; // Ꮊ → Ꮊ
      case 0x13BB:
        return 0x13BB; // Ꮋ → Ꮋ
      case 0x13BC:
        return 0x13BC; // Ꮌ → Ꮌ
      case 0x13BD:
        return 0x13BD; // Ꮍ → Ꮍ
      case 0x13BE:
        return 0x13BE; // Ꮎ → Ꮎ
      case 0x13BF:
        return 0x13BF; // Ꮏ → Ꮏ
      case 0x13C0:
        return 0x13C0; // Ꮐ → Ꮐ
      case 0x13C1:
        return 0x13C1; // Ꮑ → Ꮑ
      case 0x13C2:
        return 0x13C2; // Ꮒ → Ꮒ
      case 0x13C3:
        return 0x13C3; // Ꮓ → Ꮓ
      case 0x13C4:
        return 0x13C4; // Ꮔ → Ꮔ
      case 0x13C5:
        return 0x13C5; // Ꮕ → Ꮕ
      case 0x13C6:
        return 0x13C6; // Ꮖ → Ꮖ
      case 0x13C7:
        return 0x13C7; // Ꮗ → Ꮗ
      case 0x13C8:
        return 0x13C8; // Ꮘ → Ꮘ
      case 0x13C9:
        return 0x13C9; // Ꮙ → Ꮙ
      case 0x13CA:
        return 0x13CA; // Ꮚ → Ꮚ
      case 0x13CB:
        return 0x13CB; // Ꮛ → Ꮛ
      case 0x13CC:
        return 0x13CC; // Ꮜ → Ꮜ
      case 0x13CD:
        return 0x13CD; // Ꮝ → Ꮝ
      case 0x13CE:
        return 0x13CE; // Ꮞ → Ꮞ
      case 0x13CF:
        return 0x13CF; // Ꮟ → Ꮟ
      case 0x13D0:
        return 0x13D0; // Ꮠ → Ꮠ
      case 0x13D1:
        return 0x13D1; // Ꮡ → Ꮡ
      case 0x13D2:
        return 0x13D2; // Ꮢ → Ꮢ
      case 0x13D3:
        return 0x13D3; // Ꮣ → Ꮣ
      case 0x13D4:
        return 0x13D4; // Ꮤ → Ꮤ
      case 0x13D5:
        return 0x13D5; // Ꮥ → Ꮥ
      case 0x13D6:
        return 0x13D6; // Ꮦ → Ꮦ
      case 0x13D7:
        return 0x13D7; // Ꮧ → Ꮧ
      case 0x13D8:
        return 0x13D8; // Ꮨ → Ꮨ
      case 0x13D9:
        return 0x13D9; // Ꮩ → Ꮩ
      case 0x13DA:
        return 0x13DA; // Ꮪ → Ꮪ
      case 0x13DB:
        return 0x13DB; // Ꮫ → Ꮫ
      case 0x13DC:
        return 0x13DC; // Ꮬ → Ꮬ
      case 0x13DD:
        return 0x13DD; // Ꮭ → Ꮭ
      case 0x13DE:
        return 0x13DE; // Ꮮ → Ꮮ
      case 0x13DF:
        return 0x13DF; // Ꮯ → Ꮯ
      case 0x13E0:
        return 0x13E0; // Ꮰ → Ꮰ
      case 0x13E1:
        return 0x13E1; // Ꮱ → Ꮱ
      case 0x13E2:
        return 0x13E2; // Ꮲ → Ꮲ
      case 0x13E3:
        return 0x13E3; // Ꮳ → Ꮳ
      case 0x13E4:
        return 0x13E4; // Ꮴ → Ꮴ
      case 0x13E5:
        return 0x13E5; // Ꮵ → Ꮵ
      case 0x13E6:
        return 0x13E6; // Ꮶ → Ꮶ
      case 0x13E7:
        return 0x13E7; // Ꮷ → Ꮷ
      case 0x13E8:
        return 0x13E8; // Ꮸ → Ꮸ
      case 0x13E9:
        return 0x13E9; // Ꮹ → Ꮹ
      case 0x13EA:
        return 0x13EA; // Ꮺ → Ꮺ
      case 0x13EB:
        return 0x13EB; // Ꮻ → Ꮻ
      case 0x13EC:
        return 0x13EC; // Ꮼ → Ꮼ
      case 0x13ED:
        return 0x13ED; // Ꮽ → Ꮽ
      case 0x13EE:
        return 0x13EE; // Ꮾ → Ꮾ
      case 0x13EF:
        return 0x13EF; // Ꮿ → Ꮿ
      case 0x13F0:
        return 0x13F0; // Ᏸ → Ᏸ
      case 0x13F1:
        return 0x13F1; // Ᏹ → Ᏹ
      case 0x13F2:
        return 0x13F2; // Ᏺ → Ᏺ
      case 0x13F3:
        return 0x13F3; // Ᏻ → Ᏻ
      case 0x13F4:
        return 0x13F4; // Ᏼ → Ᏼ
      case 0x13F5:
        return 0x13F5; // Ᏽ → Ᏽ
      case 0x13F8:
        return 0x13F0; // ᏸ → Ᏸ
      case 0x13F9:
        return 0x13F1; // ᏹ → Ᏹ
      case 0x13FA:
        return 0x13F2; // ᏺ → Ᏺ
      case 0x13FB:
        return 0x13F3; // ᏻ → Ᏻ
      case 0x13FC:
        return 0x13F4; // ᏼ → Ᏼ
      case 0x13FD:
        return 0x13F5; // ᏽ → Ᏽ

      // Cyrillic
      case 0x1C80:
        return 0x0432; // ᲀ → в
      case 0x1C81:
        return 0x0434; // ᲁ → д
      case 0x1C82:
        return 0x043E; // ᲂ → о
      case 0x1C83:
        return 0x0441; // ᲃ → с
      case 0x1C84:
        return 0x0442; // ᲄ → т
      case 0x1C85:
        return 0x0442; // ᲅ → т
      case 0x1C86:
        return 0x044A; // ᲆ → ъ
      case 0x1C87:
        return 0x0463; // ᲇ → ѣ
      case 0x1C88:
        return 0xA64B; // ᲈ → ꙋ

      // Latin
      case 0x1E9B:
        return 0x1E61; // ẛ → ṡ

      // Greek
      case 0x1FBE:
        return 0x03B9; // ι → ι
      case 0x1FD3:
        return 0x0390; // ΐ → ΐ
      case 0x1FE3:
        return 0x03B0; // ΰ → ΰ

      // Latin
      case 0xA7CE:
        return 0xA7CF; // ꟎ → ꟏
      case 0xA7D2:
        return 0xA7D3; // ꟒ → ꟓ
      case 0xA7D4:
        return 0xA7D5; // ꟔ → ꟕ

      // Cherokee
      case 0xAB70:
        return 0x13A0; // ꭰ → Ꭰ
      case 0xAB71:
        return 0x13A1; // ꭱ → Ꭱ
      case 0xAB72:
        return 0x13A2; // ꭲ → Ꭲ
      case 0xAB73:
        return 0x13A3; // ꭳ → Ꭳ
      case 0xAB74:
        return 0x13A4; // ꭴ → Ꭴ
      case 0xAB75:
        return 0x13A5; // ꭵ → Ꭵ
      case 0xAB76:
        return 0x13A6; // ꭶ → Ꭶ
      case 0xAB77:
        return 0x13A7; // ꭷ → Ꭷ
      case 0xAB78:
        return 0x13A8; // ꭸ → Ꭸ
      case 0xAB79:
        return 0x13A9; // ꭹ → Ꭹ
      case 0xAB7A:
        return 0x13AA; // ꭺ → Ꭺ
      case 0xAB7B:
        return 0x13AB; // ꭻ → Ꭻ
      case 0xAB7C:
        return 0x13AC; // ꭼ → Ꭼ
      case 0xAB7D:
        return 0x13AD; // ꭽ → Ꭽ
      case 0xAB7E:
        return 0x13AE; // ꭾ → Ꭾ
      case 0xAB7F:
        return 0x13AF; // ꭿ → Ꭿ
      case 0xAB80:
        return 0x13B0; // ꮀ → Ꮀ
      case 0xAB81:
        return 0x13B1; // ꮁ → Ꮁ
      case 0xAB82:
        return 0x13B2; // ꮂ → Ꮂ
      case 0xAB83:
        return 0x13B3; // ꮃ → Ꮃ
      case 0xAB84:
        return 0x13B4; // ꮄ → Ꮄ
      case 0xAB85:
        return 0x13B5; // ꮅ → Ꮅ
      case 0xAB86:
        return 0x13B6; // ꮆ → Ꮆ
      case 0xAB87:
        return 0x13B7; // ꮇ → Ꮇ
      case 0xAB88:
        return 0x13B8; // ꮈ → Ꮈ
      case 0xAB89:
        return 0x13B9; // ꮉ → Ꮉ
      case 0xAB8A:
        return 0x13BA; // ꮊ → Ꮊ
      case 0xAB8B:
        return 0x13BB; // ꮋ → Ꮋ
      case 0xAB8C:
        return 0x13BC; // ꮌ → Ꮌ
      case 0xAB8D:
        return 0x13BD; // ꮍ → Ꮍ
      case 0xAB8E:
        return 0x13BE; // ꮎ → Ꮎ
      case 0xAB8F:
        return 0x13BF; // ꮏ → Ꮏ
      case 0xAB90:
        return 0x13C0; // ꮐ → Ꮐ
      case 0xAB91:
        return 0x13C1; // ꮑ → Ꮑ
      case 0xAB92:
        return 0x13C2; // ꮒ → Ꮒ
      case 0xAB93:
        return 0x13C3; // ꮓ → Ꮓ
      case 0xAB94:
        return 0x13C4; // ꮔ → Ꮔ
      case 0xAB95:
        return 0x13C5; // ꮕ → Ꮕ
      case 0xAB96:
        return 0x13C6; // ꮖ → Ꮖ
      case 0xAB97:
        return 0x13C7; // ꮗ → Ꮗ
      case 0xAB98:
        return 0x13C8; // ꮘ → Ꮘ
      case 0xAB99:
        return 0x13C9; // ꮙ → Ꮙ
      case 0xAB9A:
        return 0x13CA; // ꮚ → Ꮚ
      case 0xAB9B:
        return 0x13CB; // ꮛ → Ꮛ
      case 0xAB9C:
        return 0x13CC; // ꮜ → Ꮜ
      case 0xAB9D:
        return 0x13CD; // ꮝ → Ꮝ
      case 0xAB9E:
        return 0x13CE; // ꮞ → Ꮞ
      case 0xAB9F:
        return 0x13CF; // ꮟ → Ꮟ
      case 0xABA0:
        return 0x13D0; // ꮠ → Ꮠ
      case 0xABA1:
        return 0x13D1; // ꮡ → Ꮡ
      case 0xABA2:
        return 0x13D2; // ꮢ → Ꮢ
      case 0xABA3:
        return 0x13D3; // ꮣ → Ꮣ
      case 0xABA4:
        return 0x13D4; // ꮤ → Ꮤ
      case 0xABA5:
        return 0x13D5; // ꮥ → Ꮥ
      case 0xABA6:
        return 0x13D6; // ꮦ → Ꮦ
      case 0xABA7:
        return 0x13D7; // ꮧ → Ꮧ
      case 0xABA8:
        return 0x13D8; // ꮨ → Ꮨ
      case 0xABA9:
        return 0x13D9; // ꮩ → Ꮩ
      case 0xABAA:
        return 0x13DA; // ꮪ → Ꮪ
      case 0xABAB:
        return 0x13DB; // ꮫ → Ꮫ
      case 0xABAC:
        return 0x13DC; // ꮬ → Ꮬ
      case 0xABAD:
        return 0x13DD; // ꮭ → Ꮭ
      case 0xABAE:
        return 0x13DE; // ꮮ → Ꮮ
      case 0xABAF:
        return 0x13DF; // ꮯ → Ꮯ
      case 0xABB0:
        return 0x13E0; // ꮰ → Ꮰ
      case 0xABB1:
        return 0x13E1; // ꮱ → Ꮱ
      case 0xABB2:
        return 0x13E2; // ꮲ → Ꮲ
      case 0xABB3:
        return 0x13E3; // ꮳ → Ꮳ
      case 0xABB4:
        return 0x13E4; // ꮴ → Ꮴ
      case 0xABB5:
        return 0x13E5; // ꮵ → Ꮵ
      case 0xABB6:
        return 0x13E6; // ꮶ → Ꮶ
      case 0xABB7:
        return 0x13E7; // ꮷ → Ꮷ
      case 0xABB8:
        return 0x13E8; // ꮸ → Ꮸ
      case 0xABB9:
        return 0x13E9; // ꮹ → Ꮹ
      case 0xABBA:
        return 0x13EA; // ꮺ → Ꮺ
      case 0xABBB:
        return 0x13EB; // ꮻ → Ꮻ
      case 0xABBC:
        return 0x13EC; // ꮼ → Ꮼ
      case 0xABBD:
        return 0x13ED; // ꮽ → Ꮽ
      case 0xABBE:
        return 0x13EE; // ꮾ → Ꮾ
      case 0xABBF:
        return 0x13EF; // ꮿ → Ꮿ

      // Latin
      case 0xFB05:
        return 0xFB06; // ﬅ → ﬆ

      // Beria_Erfe
      case 0x16EA0:
        return 0x16EBB; // 𖺠 → 𖺻
      case 0x16EA1:
        return 0x16EBC; // 𖺡 → 𖺼
      case 0x16EA2:
        return 0x16EBD; // 𖺢 → 𖺽
      case 0x16EA3:
        return 0x16EBE; // 𖺣 → 𖺾
      case 0x16EA4:
        return 0x16EBF; // 𖺤 → 𖺿
      case 0x16EA5:
        return 0x16EC0; // 𖺥 → 𖻀
      case 0x16EA6:
        return 0x16EC1; // 𖺦 → 𖻁
      case 0x16EA7:
        return 0x16EC2; // 𖺧 → 𖻂
      case 0x16EA8:
        return 0x16EC3; // 𖺨 → 𖻃
      case 0x16EA9:
        return 0x16EC4; // 𖺩 → 𖻄
      case 0x16EAA:
        return 0x16EC5; // 𖺪 → 𖻅
      case 0x16EAB:
        return 0x16EC6; // 𖺫 → 𖻆
      case 0x16EAC:
        return 0x16EC7; // 𖺬 → 𖻇
      case 0x16EAD:
        return 0x16EC8; // 𖺭 → 𖻈
      case 0x16EAE:
        return 0x16EC9; // 𖺮 → 𖻉
      case 0x16EAF:
        return 0x16ECA; // 𖺯 → 𖻊
      case 0x16EB0:
        return 0x16ECB; // 𖺰 → 𖻋
      case 0x16EB1:
        return 0x16ECC; // 𖺱 → 𖻌
      case 0x16EB2:
        return 0x16ECD; // 𖺲 → 𖻍
      case 0x16EB3:
        return 0x16ECE; // 𖺳 → 𖻎
      case 0x16EB4:
        return 0x16ECF; // 𖺴 → 𖻏
      case 0x16EB5:
        return 0x16ED0; // 𖺵 → 𖻐
      case 0x16EB6:
        return 0x16ED1; // 𖺶 → 𖻑
      case 0x16EB7:
        return 0x16ED2; // 𖺷 → 𖻒
      case 0x16EB8:
        return 0x16ED3; // 𖺸 → 𖻓
      default:
        return Character.toLowerCase(c);
    }
  }
}
