- hosts: localhost
  gather_facts: false
  tasks:
    - name: Destroy cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        region: "{{ region }}"
        state: absent
      delegate_to: localhost
