name: "Set up caches"
description: "Set up cached resources"

runs:
  using: "composite"
  steps:
    - name: Cache/Restore cached gradle files
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/jdks
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('versions.lock', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
