name: Dependabot Dependency Submission (gradle)

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-for-build

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4