name: "Run checks: dev-tools/scripts (python)"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
      - 'branch_10x'
    paths:
      - '.github/workflows/run-checks-python.yml'
      - 'dev-tools/scripts/**'

  push:
    branches:
      - 'main'
      - 'branch_10x'
    paths:
      - '.github/workflows/run-checks-python.yml'
      - 'dev-tools/scripts/**'

permissions: {}

jobs:
  lint:
    name: Lint python scripts
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12.6"

      - name: Lint Python
        run: "cd dev-tools/scripts && make"
        env:
          RUFF_OUTPUT_FORMAT: github
