name: Run smokeTestRelease.py against a release candidate

on:
  workflow_dispatch:
    inputs:
      artifacts-url:
        description: 'URL to artifacts, example: https://dist.apache.org/repos/dist/dev/lucene/lucene-...'
        type: string
        required: true

      run-tests:
        description: "Include a full test run"
        type: boolean
        required: false
        default: false

jobs:
  smokeTestRelease:
    name: "smoke jdk ${{ matrix.java-version }}, ${{ matrix.os }}"

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ '11', '17', '21', '22-ea' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          # TODO: shouldn't be needed but smoketester checks java version and we're on main.
          ref: 'branch_9_10'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: jdk
          check-latest: true
          java-version: |
            ${{ matrix.java-version }}
            11

      - name: Run smoke tester with Java ${{ matrix.java-version }} and (${{ inputs.artifacts-url }})
        run: |
          echo "All installed JDKs:"
          set | grep "JAVA"

          echo "Build matrix-picked JDK:"
          RUNTIME_JAVA_HOME_VAR=JAVA_HOME_`echo ${{ matrix.java-version }} | egrep --only "[0-9]+"`_X64
          echo ${RUNTIME_JAVA_HOME_VAR} points at ${!RUNTIME_JAVA_HOME_VAR}

          python3 -u dev-tools/scripts/smokeTestRelease.py ${{ inputs.artifacts-url }} \
            ${{ inputs.run-tests && '' || '-Dtests.filter="@skipall"' }} \
            -Druntime.java.home=${!RUNTIME_JAVA_HOME_VAR}
